set guzzle requirement to ^7
digiti/airtable-api-php pull request #1
Opened 2023-10-19 15:43 UTC by spencer95

2023-10-19 15:44 UTC, spencer95 commented
guzzle 7

2023-10-20 14:15 UTC, lammensj requested changes

2023-10-20 14:15 UTC, lammensj commented on composer.json
> +        "guzzlehttp/guzzle": "^7",
To be backwards compatible, I would advice to use `^6.3 || ^7`

2024-01-28 17:39 UTC, clairemistry commented
I really need this change too in my  Drupal 10 project.  Could we get this merged in? Thank you so much

2024-02-11 15:00 UTC, lammensj commented
I don't work at this company anymore, hence I don't have write-access. I'll reach out to my former colleagues, keep you posted.

2024-02-11 15:07 UTC, lammensj commented
Done!

2024-02-11 15:08 UTC, closed without merging